version: '3.1'

services:

  webapp:
    container_name: api_descomplica
    build: .
    entrypoint: .docker/entrypoint.sh
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/api
    networks:
      - api
    
  db:
    container_name: db_descomplica
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - api

  proxy:
    container_name: nginx
    image: nginx
    ports:
      - 80:${NGINX_PORT}
    depends_on:
      - webapp
    networks:
      - api

networks:
  api:
    driver: bridge
  