version: '3.1'

services:

  api:
    container_name: api_graph
    build: .
    ports:
      - "${PORT_API}:${PORT_API}"
    volumes:
      - .:/home/api
  db:
    container_name: graph_db
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
