version: '3.1'

services:

  api_desc:
    container_name: api_descomplica
    build: .
    entrypoint: .docker/entrypoint.sh
    volumes:
      - .:/home/api
    networks:
      - net_api
    
  db:
    container_name: db_descomplica
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - net_api

  proxy:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:${NGINX_PORT}
    depends_on:
      - api_desc
    networks:
      - net_api

networks:
  net_api:
    driver: bridge
  