version: '3.1'

services:

  api:
    container_name: api_descomplica
    build: .
    entrypoint: .docker/entrypoint.sh
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/api
  db:
    container_name: db_descomplica
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
